# Generated by Django 5.2.1 on 2026-03-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
