# Generated by Django 5.2.1 on 2026-03-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_product_image_alter_vendor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/'),
        ),
    ]
